/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Faiqoh
 */
public class praktikum2 extends javax.swing.JFrame {

    /**
     * Creates new form praktikum2
     */
    public praktikum2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtruang = new javax.swing.JTextField();
        jtxtjml = new javax.swing.JTextField();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtjadwal = new javax.swing.JTextField();
        jtxtsarana = new javax.swing.JTextField();
        jtxtfasilitas = new javax.swing.JTextField();
        jtxtbiaya = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jcbim = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Pemilihan Paket Bimbingan Belajar Ganesha Operation");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 340, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Pilih Paket");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 80, 90, 20);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Deskripsi"));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Jumlah Siswa");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 90, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Ruang Kelas");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 30, 90, 36);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Waktu ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 123, 90, 34);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Jadwal");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 170, 90, 35);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Sarana");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 214, 90, 35);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Fasilitas");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 261, 90, 34);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Biaya");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 306, 106, 36);

        jtxtruang.setEnabled(false);
        jPanel1.add(jtxtruang);
        jtxtruang.setBounds(134, 28, 230, 35);

        jtxtjml.setEnabled(false);
        jPanel1.add(jtxtjml);
        jtxtjml.setBounds(134, 74, 230, 38);

        jtxtwaktu.setEnabled(false);
        jPanel1.add(jtxtwaktu);
        jtxtwaktu.setBounds(134, 123, 230, 34);

        jtxtjadwal.setEnabled(false);
        jPanel1.add(jtxtjadwal);
        jtxtjadwal.setBounds(134, 168, 230, 35);

        jtxtsarana.setEnabled(false);
        jPanel1.add(jtxtsarana);
        jtxtsarana.setBounds(134, 214, 230, 35);

        jtxtfasilitas.setEnabled(false);
        jPanel1.add(jtxtfasilitas);
        jtxtfasilitas.setBounds(134, 260, 230, 35);

        jtxtbiaya.setEnabled(false);
        jPanel1.add(jtxtbiaya);
        jtxtbiaya.setBounds(134, 306, 230, 36);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 120, 380, 380);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        jcbim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "Silver", "Gold", "Platinum" }));
        jcbim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbimActionPerformed(evt);
            }
        });
        jPanel3.add(jcbim);
        jcbim.setBounds(220, 70, 160, 40);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 510, 540);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 510, 540);

        setBounds(0, 0, 523, 573);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbimActionPerformed
        // TODO add your handling code here:
        if(jcbim.getSelectedItem().equals("Silver")){
            jtxtruang.setText("Kelas Nakula");
            jtxtjml.setText("20 Siswa");
            jtxtwaktu.setText("14.00 - 17.00");
            jtxtjadwal.setText("Senin-Selasa");
            jtxtsarana.setText("AC, Kursi, TV, Ptoyektor");
            jtxtfasilitas.setText("Bank Soal + Materi ");
            jtxtbiaya.setText("Rp. 3.000.000");}
        else if(jcbim.getSelectedItem().equals("Gold")){
            jtxtruang.setText("Kelas Sadewa");
            jtxtjml.setText("15 Siswa");
            jtxtwaktu.setText("13.00 - 16.00");
            jtxtjadwal.setText("Selas - Rabu");
            jtxtsarana.setText("Bank Soal + Materi + Kumpulan Rumus");
            jtxtfasilitas.setText("AC, Kursi, TV, Ptoyektor, PC");
            jtxtbiaya.setText("Rp. 4.000.000");}
        else if(jcbim.getSelectedItem().equals("Platinum")){
            jtxtruang.setText("Kelas Arjuna");
            jtxtjml.setText("10 Siswa");
            jtxtwaktu.setText("13.00 - 16.00");
            jtxtjadwal.setText("Kamis - Jum'at");
            jtxtsarana.setText("AC, Kursi, TV, Ptoyektor, PC, Card");
            jtxtfasilitas.setText("Bank Soal + Materi + Kumpulan Rumus + Video Pembelajaran");
            jtxtbiaya.setText("Rp. 5.000.000");}
    }//GEN-LAST:event_jcbimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new praktikum2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jcbim;
    private javax.swing.JTextField jtxtbiaya;
    private javax.swing.JTextField jtxtfasilitas;
    private javax.swing.JTextField jtxtjadwal;
    private javax.swing.JTextField jtxtjml;
    private javax.swing.JTextField jtxtruang;
    private javax.swing.JTextField jtxtsarana;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
